# Generated by Django 3.2.1 on 2021-08-01 10:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.CharField(default=None, max_length=10)),
                ('side', models.CharField(default=None, max_length=4)),
                ('date_of_open', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_of_close', models.DateTimeField(blank=True, default=None, null=True)),
                ('open_price', models.FloatField(default=None)),
                ('close_price', models.FloatField(blank=True, default=None, null=True)),
            ],
        ),
    ]
